### PR TITLE
Fixed #576

### LINKED ISSUE #576: Issues with Vendor shipping from Admin end
Go to admin dashboard>>MultiVendorX>>Vendors, select vendor>>Vendor Shipping. Here there are some issues with configuring vendor shipping. 

1. Under shipping by zone, in shipping methods section the css is no correct (https://prnt.sc/ysj3LqBQCbXx). there is no data shown under the Action, enabled and description column. 
2. In add shipping method option the sidebar scrolling do not work. (https://watch.screencastify.com/v/sSNJMYorz2ZcamQ9hSjM) 
3. Also  after choosing a shipping option from the dropdown, there is no option to come back to the previous section. (https://prnt.sc/p_2WF-Ddi5FZ)

### PR DESCRIPTION
**Pull request by user-promi**

### CODE REVIEW

**Comment by Sangi0** [comment]
https://www.awesomescreenshot.com/video/22777171?key=ca3c75c367ad02ad5a0b315041f087eb

File: mvx-modules/src/components/admin/classes/class-mvx-vendor-manage.js [hunk 1]
```diff
@@ -1560,6 +1560,9 @@ class MVXBackendVendor extends React.Component {
 							Object.keys(this.state.data_zone_in_shipping)
 								.length > 0 ? (
 								<div>
+									<Link className="mvx-back-btn" to={`?page=mvx#&submenu=vendor&ID=${name.get('ID')}&name=vendor-shipping`}>
+										<i className="mvx-font icon-back"></i>Back
```
Comment (moumitahalder) [inline mvx-modules/src/components/admin/classes/class-mvx-vendor-manage.js]: plz add string support

**Review by moumitahalder — CHANGES_REQUESTED** [review]
